// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzgbtbnnsphqqqttfrzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Z2J0Ym5uc3BocXFxdHRmcnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Njc5MDcsImV4cCI6MjA1ODQ0MzkwN30.ybfsJge6TOcfn25kp2clZ5PX-NgrCHTuC65f74v-LCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);